Add Kingston Communications(KCOM)
cloudflare/isbgpsafeyet.com pull request #637
Opened 2022-11-16 14:44 UTC by thomasdouwes

Tested with [isbgpsafeyet.com](https://isbgpsafeyet.com)

2023-02-27 23:27 UTC, digizeph commented on data/operators.csv
> +Kingston Communications,ISP,,unsafe,12390,5388
AS12390 has signed all their prefixes. Suggest change to `partially safe` category.
```suggestion
Kingston Communications,ISP,signed,partially safe,12390,5388
```

2023-02-27 23:43 UTC, digizeph approved these changes

2023-02-28 11:40 UTC, thomasdouwes commented
I received an email saying there was a comment on this pull request but I can't find it? what should I do?

2023-02-28 14:30 UTC, digizeph commented
@thomasdouwes Thank you for your PR, and sorry for the confusion! we will move forward merging your pull request in the coming days. no action needed from you.

2023-02-28 14:46 UTC, thomasdouwes commented
Ok, do I not need to change to signed/partially safe then? I checked on he.net and AS12390 is signed just not filtering. Also, oddly they used to filter but stopped before I made the PR

2023-02-28 16:09 UTC, digizeph commented
No need to change your PR. 
In terms of using `partially safe` label, we want to make sure at least some degree of invalid filtering is happening based on our observation. They seem to completely stop filtering RPKI invalid from July 2022. See here: https://stats.labs.apnic.net/rpki/AS12390

2023-02-28 16:55 UTC, digizeph commented on data/operators.csv
> +Kingston Communications,ISP,,unsafe,12390,5388
You are right about them signing their prefixes. (Sorry about the back-and-forth on the changes, it's on me!)
```suggestion
Kingston Communications,ISP,signed,unsafe,12390,5388
```

2023-02-28 17:10 UTC, digizeph requested changes
There is already a AS12390 in the line 240. Should make edits on that line instead.

2023-03-05 15:34 UTC, digizeph approved these changes

2023-03-05 15:34 UTC, merged